### ISSUE TITLE
Review code

### ISSUE THREAD

**Issue by hoangph-1744** [linhdb-2149/flowers_retrieval_streamlit#1]
- import đoạn này vào làm gì em, giờ xử lý trên grpc của serving hết mà https://github.com/linhdb-2149/flowers_retrieval_streamlit/blob/83fc5d07422c23845737932099b03c04f4c7dc4f/utils.py#L20-L28

- đoạn này làm gì mà phải comment lại thế, đoạn nào ko dùng em xóa đi https://github.com/linhdb-2149/flowers_retrieval_streamlit/blob/83fc5d07422c23845737932099b03c04f4c7dc4f/utils.py#L120-L123

- nhớ check lại pep8 nhé, dòng dài quá thì ngắt xuống, đoạn trên thừa pdb thì xóa đi em https://github.com/linhdb-2149/flowers_retrieval_streamlit/blob/master/utils.py#L184

- xóa hết chỗ cmt này nhé https://github.com/linhdb-2149/flowers_retrieval_streamlit/blob/83fc5d07422c23845737932099b03c04f4c7dc4f/utils.py#L232-L260 && https://github.com/linhdb-2149/flowers_retrieval_streamlit/blob/83fc5d07422c23845737932099b03c04f4c7dc4f/utils.py#L290-L301

- chỉnh lại 1 vài chỗ về pep8 nữa là ok

**Comment by linhdb-2149** [comment]
ok ạ
